### PR TITLE
Fixes #46

### LINKED ISSUE #46: Add option for switching from multi-line parsing (default) to single-line parsing
In order for humble me to have its will, and also to be able to generate the changelog that I want, I need single line parsing.

The rationale behind this being that
- each line prefixed by a hyphen in my commit message refers to a specific change and may optionally reference an issue including also the type of change, e.g. api(change), deprecates, feature, fix(es) and so on
- something which will be singled out by pretty=%s, but with the new logArguments in place, I can use --pretty=%B and everything is fine
- each non prefixed line can be silently ignored and must not be included in the changelog

Without this option I will not be able to gather non issue related changes in the changelog as it

  a) would make the resulting regexp overly complex, and
  b) would not even be possible to achieve with regexp alone

Therefore, I propose another option to grunt-changelog, namely
- multiline : true (default) | false

On true, grunt-changelog will expose its current standard behaviour.

On false, grunt-changelog will use a different parser for the changelog that will run tests against the section regexps line by line instead of applying them globally on the whole of the log returned from git/passed in as a parameter.

Please note that this requires #39 to be merged as the following PR will build on that.

### PR DESCRIPTION
**Pull request by silkentrance**
- fixes #46:adds multiline option for switching log parsing behaviour

Needs PR #39 as it is based on the custom sections patch.

Readme still needs some work, documenting the new option.

### CODE REVIEW

**Comment by silkentrance** [comment]
@ericmatthys Please have a look and tell me if this is what you want. The readme still needs to be update but that is something I can do as soon as the patch is ready. This time it is the correct issue and the correct branch *SIGH*...

**Comment by silkentrance** [comment]
@mischah Perhaps you might want to have a look at this?

**Comment by mischah** [comment]
Looks like a lot of code for a usecase which seems to a bit exotic to me :laughing: 
But it doesn’t mean that this one won’t be merged just because I don’t feel the need for this.

Any thoughts on that @ericmatthys?

**Comment by ericmatthys** [comment]
In general, the project has tried to be flexible, which is why templating is included in the first place. However, at some point, we have to draw a line and say this is better off for a fork rather than the main project. I'm tempted to put this on the other side of that line just because it does seem like a niche case and it adds a fair bit of complexity to achieve it.

**Comment by silkentrance** [comment]
While I don´t think that singleLineParser with its additional 30 or so lines of extra code adds that much complexity to the project, feel free to reject this as you like. I might consider creating a fork from this, for the time being I will simply use my repository instead.

**Comment by silkentrance** [comment]
@ericmatthys it seems as if no one needs this change. And since I have moved on, I will close this in order to get rid of it.

**Pull request closed without merging**
